version: '2'
services:
    truckersloyaltyprogram-app:
        image: truckersloyaltyprogram
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://truckersloyaltyprogram-mysql:3306/truckersloyaltyprogram?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    truckersloyaltyprogram-mysql:
        extends:
            file: mysql.yml
            service: truckersloyaltyprogram-mysql
